language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t andr095/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true andr095/react-test npm run test -- --coverage

after_success:
  - docker build -t andr095/multi-client ./client
  - docker build -t andr095/multi-nginx ./nginx
  - docker build -t andr095/multi-server ./server
  - docker build -t andr095/multi-worker ./worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1" 
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-414579692089"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"