apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: fibonacci-com-tls
spec:
  secretName: fibonacci-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: fibonacci.digitalservice.in.ua
  dnsNames:
    - fibonacci.digitalservice.in.ua
    - www.fibonacci.digitalservice.in.ua